/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/endpoints/player-hub": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_endpoints_player_hub_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/endpoints/team-hub": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Team Catalog
         * @description Static Team Hub catalog: tabs and dataset metadata.
         */
        get: operations["team_catalog_api_endpoints_team_hub_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Featured Players */
        get: operations["featured_players_api_players_featured_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Players */
        get: operations["search_players_api_players_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{identifier}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Summary */
        get: operations["player_summary_api_players_identifier_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{identifier}/seasons/{season_end_year}/{dataset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Season Dataset */
        get: operations["player_season_dataset_api_players_identifier_seasons_season_end_year_dataset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{identifier}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Player Dataset */
        get: operations["export_player_dataset_api_players_identifier_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{identifier}/{dataset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Dataset */
        get: operations["player_dataset_api_players_identifier_dataset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Featured Teams */
        get: operations["featured_teams_api_teams_featured_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Teams */
        get: operations["search_teams_api_teams_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{identifier}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team Summary */
        get: operations["team_summary_api_teams_identifier_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{identifier}/seasons/{season_end_year}/{dataset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team Season Dataset */
        get: operations["team_season_dataset_api_teams_identifier_seasons_season_end_year_dataset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{identifier}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Team Dataset */
        get: operations["export_team_dataset_api_teams_identifier_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{identifier}/{dataset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team Dataset */
        get: operations["team_dataset_api_teams_identifier_dataset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ColumnMeta
         * @description Presentation metadata for one response column.
         */
        ColumnMeta: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Default Visible
             * @default true
             */
            default_visible: boolean;
            /**
             * Numeric
             * @default false
             */
            numeric: boolean;
        };
        /**
         * DatasetCatalogEntry
         * @description HTTP-facing metadata for one Player Hub dataset.
         */
        DatasetCatalogEntry: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Endpoint Name */
            endpoint_name: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "player" | "season";
            /** Description */
            description: string;
            /** Columns */
            columns: components["schemas"]["ColumnMeta"][];
            /** Default Visible Columns */
            default_visible_columns?: string[];
            /**
             * Supports Export
             * @default true
             */
            supports_export: boolean;
        };
        /**
         * EndpointRowsResponse
         * @description Rows plus presentation metadata for a dataset endpoint.
         */
        EndpointRowsResponse: {
            /** Dataset */
            dataset: string;
            /** Endpoint Name */
            endpoint_name: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Row Count */
            row_count: number;
            /** Columns */
            columns: components["schemas"]["ColumnMeta"][];
            /** Default Visible Columns */
            default_visible_columns: string[];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /**
         * FeaturedAthlete
         * @description Featured player card payload.
         */
        FeaturedAthlete: {
            /** Name */
            name: string;
            /** Identifier */
            identifier: string;
            /** Leagues */
            leagues: string[];
            /** Blurb */
            blurb?: string | null;
        };
        /**
         * FeaturedAthletesResponse
         * @description Featured players for the Player Hub landing page.
         */
        FeaturedAthletesResponse: {
            /** Athletes */
            athletes: components["schemas"]["FeaturedAthlete"][];
        };
        /**
         * FeaturedTeam
         * @description Featured team card payload.
         */
        FeaturedTeam: {
            /** Name */
            name: string;
            /** Identifier */
            identifier: string;
            /** Leagues */
            leagues: string[];
            /** Blurb */
            blurb?: string | null;
        };
        /**
         * FeaturedTeamsResponse
         * @description Featured teams for the Team Hub landing page.
         */
        FeaturedTeamsResponse: {
            /** Teams */
            teams: components["schemas"]["FeaturedTeam"][];
        };
        /**
         * FranchiseArcPoint
         * @description One season on a franchise win/loss arc.
         */
        FranchiseArcPoint: {
            /** Season End Year */
            season_end_year: number;
            /** Team Name */
            team_name?: string | null;
            /** Wins */
            wins?: number | null;
            /** Losses */
            losses?: number | null;
            /** Win Pct */
            win_pct?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PlayerHubCatalog
         * @description Top-level Player Hub catalog response: tabs and dataset metadata for the player-hub UI shell.
         */
        PlayerHubCatalog: {
            /** Tabs */
            tabs: components["schemas"]["PlayerHubTab"][];
            /** Datasets */
            datasets: components["schemas"]["DatasetCatalogEntry"][];
        };
        /**
         * PlayerHubSummary
         * @description Aggregated overview payload for one player.
         */
        PlayerHubSummary: {
            /** Identifier */
            identifier: string;
            /** Display Name */
            display_name: string;
            /** Leagues */
            leagues: string[];
            /** Default Season */
            default_season: number | null;
            /** Available Seasons */
            available_seasons: number[];
            /** Hero Stats */
            hero_stats: {
                [key: string]: unknown;
            };
            career: components["schemas"]["EndpointRowsResponse"];
        };
        /**
         * PlayerHubTab
         * @description A tab and its backing datasets in the Player Hub.
         */
        PlayerHubTab: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "player" | "season";
            /** Datasets */
            datasets: string[];
            /** Default Dataset */
            default_dataset: string;
        };
        /**
         * PlayerSearchResult
         * @description One player search hit.
         */
        PlayerSearchResult: {
            /** Name */
            name: string;
            /** Identifier */
            identifier: string;
            /** Leagues */
            leagues: string[];
        };
        /**
         * StatusResponse
         * @description Health and runtime metadata for the UI shell.
         */
        StatusResponse: {
            /** Ok */
            ok: boolean;
            /** Endpoint Count */
            endpoint_count: number;
        };
        /**
         * TeamDatasetCatalogEntry
         * @description HTTP-facing metadata for one Team Hub dataset.
         */
        TeamDatasetCatalogEntry: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Endpoint Name */
            endpoint_name: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "team" | "team_season";
            /** Description */
            description: string;
            /** Columns */
            columns?: components["schemas"]["ColumnMeta"][] | null;
            /** Default Visible Columns */
            default_visible_columns?: string[] | null;
            /**
             * Supports Export
             * @default true
             */
            supports_export: boolean;
        };
        /**
         * TeamHeroStats
         * @description Current/default season headline metrics for a team.
         */
        TeamHeroStats: {
            /** Team */
            team: string;
            /** Season */
            season?: number | string | null;
            /** Wins */
            wins?: number | null;
            /** Losses */
            losses?: number | null;
            /** Win Pct */
            win_pct?: number | null;
            /** Off Rtg */
            off_rtg?: number | null;
            /** Def Rtg */
            def_rtg?: number | null;
        };
        /**
         * TeamHubCatalog
         * @description Top-level Team Hub catalog response: tabs and dataset metadata for the team-hub UI shell.
         */
        TeamHubCatalog: {
            /** Tabs */
            tabs: components["schemas"]["TeamHubTab"][];
            /** Datasets */
            datasets: components["schemas"]["TeamDatasetCatalogEntry"][];
        };
        /**
         * TeamHubSummary
         * @description Aggregated overview payload for one team.
         */
        TeamHubSummary: {
            /** Identifier */
            identifier: string;
            /** Display Name */
            display_name: string;
            /** Leagues */
            leagues: string[];
            /** Default Season */
            default_season: number | null;
            /** Available Seasons */
            available_seasons: number[];
            hero_stats: components["schemas"]["TeamHeroStats"];
            roster: components["schemas"]["EndpointRowsResponse"];
            /** Franchise Arc */
            franchise_arc: components["schemas"]["FranchiseArcPoint"][];
        };
        /**
         * TeamHubTab
         * @description A tab and its backing datasets in the Team Hub.
         */
        TeamHubTab: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "team" | "team_season";
            /** Datasets */
            datasets: string[];
            /** Default Dataset */
            default_dataset: string;
        };
        /**
         * TeamSearchResult
         * @description One team search hit.
         */
        TeamSearchResult: {
            /** Name */
            name: string;
            /** Identifier */
            identifier: string;
            /** Leagues */
            leagues: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog_api_endpoints_player_hub_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerHubCatalog"];
                };
            };
        };
    };
    team_catalog_api_endpoints_team_hub_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamHubCatalog"];
                };
            };
        };
    };
    featured_players_api_players_featured_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedAthletesResponse"];
                };
            };
        };
    };
    search_players_api_players_search_get: {
        parameters: {
            query: {
                term: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_summary_api_players_identifier_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerHubSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_season_dataset_api_players_identifier_seasons_season_end_year_dataset_get: {
        parameters: {
            query?: {
                include_inactive_games?: boolean;
            };
            header?: never;
            path: {
                identifier: string;
                season_end_year: number;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointRowsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_player_dataset_api_players_identifier_export_get: {
        parameters: {
            query: {
                dataset: string;
                season_end_year?: number | null;
                include_inactive_games?: boolean;
            };
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_dataset_api_players_identifier_dataset_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointRowsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    featured_teams_api_teams_featured_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedTeamsResponse"];
                };
            };
        };
    };
    search_teams_api_teams_search_get: {
        parameters: {
            query: {
                term: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    team_summary_api_teams_identifier_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamHubSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    team_season_dataset_api_teams_identifier_seasons_season_end_year_dataset_get: {
        parameters: {
            query?: {
                include_inactive_games?: boolean;
            };
            header?: never;
            path: {
                identifier: string;
                season_end_year: number;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointRowsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_team_dataset_api_teams_identifier_export_get: {
        parameters: {
            query: {
                dataset: string;
                season_end_year?: number | null;
                include_inactive_games?: boolean;
            };
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    team_dataset_api_teams_identifier_dataset_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointRowsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
